// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA51IGwdRv02fG8gb6Erbzg7CShXXXERkQ',
    appId: '1:895408150567:web:59e8017eeb411f2c7f5602',
    messagingSenderId: '895408150567',
    projectId: 'sample1',
    authDomain: 'sample1.firebaseapp.com',
    storageBucket: 'sample1.appspot.com',
    measurementId: 'G-WKQTKLN35V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9FFdHl-Z-qbDrCrSh-FldO6UjZkSvDo',
    appId: '1:895408150567:android:85d7d101f81bfd777f5602',
    messagingSenderId: '895408150567',
    projectId: 'sample1',
    storageBucket: 'sample1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJK4nzZ44aU_hLJKOskrDDAwMqJ75LFBE',
    appId: '1:895408150567:ios:7bf32242ff493f5d7f5602',
    messagingSenderId: '895408150567',
    projectId: 'sample1',
    storageBucket: 'sample1.appspot.com',
    iosBundleId: 'com.nsl.sample',
  );
}
