name: response_wrapper
description: Help to hit dio call.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 4.0.6
  plugin_platform_interface: ^2.0.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.response_wrapper
        pluginClass: ResponseWrapperPlugin
      ios:
        pluginClass: ResponseWrapperPlugin
